version: "3.7"
services:
  # The Go App, 
  # container_name is related with Makefile in order to run commands inside the container
  <CONTAINER_NAME_REPLACE>:
    container_name: <CONTAINER_NAME_REPLACE>
    build:
      context: .
      target: dev
    volumes:
      - .:/opt/app/api:rw,delegated
    networks:
      - <CONTAINER_NAME_REPLACE>_network
    ports:
      - 8080:8080
      - 2345:2345
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE  


      
networks:
  <CONTAINER_NAME_REPLACE>_network:
    name: <CONTAINER_NAME_REPLACE>_network