version: "3.7"
services:
  # The Go App, 
  # container_name is related with Makefile in order to run commands inside the container
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '8080:8080'
    volumes:
      - .:/opt/app/api