// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"<MODULE_URL_REPLACE>/pkg/users/application/registeruser"
)

// Injectors from wire.go:

func Wire() registeruser.CommandHandler {
	inmemoryUsersRepository := NewInmemoryUsersRepository()
	service := NewRegisterUserService(inmemoryUsersRepository)
	commandHandler := NewRegisterUserCommandHandler(service)
	return commandHandler
}
